<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpenseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpenseRepository extends EntityRepository
{
    public function search($description,$amount,$startDate,$endDate)
    {
        $qb = $this->createQueryBuilder('o');

        $qb->select('o');

        if($description != null & $description != ""){
            $qb->andWhere('o.description LIKE :description')
                ->setParameter('description',$description)
            ;
        }

        if($amount != null & $amount != ""){
            $qb->andWhere('o.amount LIKE :amount')
                ->setParameter('amount',$amount)
            ;
        }
        return $qb->getQuery()->getResult();
    }
}
