<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    public function search($startDate,$endDate)
    {
        $qb = $this->createQueryBuilder('o');

        $qb->select('o')
            ->andWhere('o.dateTime BETWEEN :startDate AND :endDate')
            ->setParameter('startDate',$startDate)
            ->setParameter('endDate',$endDate)
            ;
        return $qb->getQuery()->getResult();
    }
}
