<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getSuggestions($itemCode){
        $qb = $this->createQueryBuilder('o');

        $qb
            ->select('o')
            ->where('o.itemCode LIKE :itemCode')
            ->setParameter('itemCode',"%".$itemCode."%")
            ->setMaxResults(10)
        ;

        return $qb->getQuery()->getResult();

    }
}
